# Generated by Django 3.2.4 on 2021-07-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
